apps/escuela/urls.py
from . import views
from apps.escuela.views import EscuelaPagosList, EscuelaPagoCreate, EscuelaAsistenciaCreate
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


urlpatterns = [

   
    path('lista_pagos_escuela/', login_required(EscuelaPagosList.as_view()),
         name='lista_pagos_escuela'),
    
    path('pagos_escuela/', login_required(EscuelaPagoCreate.as_view()), name='pagos_escuela'),
    
    path('asistencia/', login_required(EscuelaAsistenciaCreate.as_view()),
         name='asistencia'),


   



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

triaCba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
  
    path('escuela/', include('apps.escuela.urls')),
    path('registro/', include('apps.registro.urls')),
    path('asociado/', include('apps.socio.urls')),
    path('inscripcion/', include('apps.inscripcion.urls')),
    path('', include('apps.usuarios.urls')),
    path('entrenadores/', include('apps.entrenadores.urls')),
    path('emails/', include('apps.emails.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),

    
    
    # path('', LoginView.as_view(template_name='accounts/login.html'), name = 'login')
    
    
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "apps.socio.views.error_404_view"
handler404 = "apps.usuarios.views.error_404_view"
handler404 = "apps.inscripcion.views.error_404_view"
handler404 = "apps.registro.views.error_404_view"
handler404 = "apps.emails.views.error_404_view"

apps/escuela/models.py
from django.db import models
from apps.socio.models import Asociado
from datetime import date

# Create your models here.


class EscuelaFormasPago(models.Model):
    formaPago = models.CharField(max_length=40)

    

    def __str__(self):
        return f"{self.formaPago}"


class EscuelaCosto(models.Model):
    
    formaPago = models.ForeignKey(EscuelaFormasPago, default=1, on_delete=models.CASCADE, null=True)
    precio = models.IntegerField()
    
    def __str__(self):
        return f"{self.formaPago} - ${self.precio}"
    

class EscuelaPagos(models.Model):
    asociado = models.ForeignKey(Asociado, null=True, blank=True,
                                        on_delete=models.CASCADE, verbose_name='Persona Asociada')
    opcionElegida = models.ForeignKey(
        EscuelaCosto, null=True, blank=True, on_delete=models.CASCADE, verbose_name="Opcion Elegida")

    tipoPago = models.CharField(
        max_length=40,  blank=True, null=True, verbose_name="Entrenador :")
    formaPago = models.CharField(
        max_length=40,  blank=True, null=True, verbose_name="Forma pago")
    montoDebeAbonar = models.IntegerField(
        null=True, blank=True, verbose_name="Monto a abonar:")
    montoAbonado = models.IntegerField(
        null=True, verbose_name="Monto Abonado:")
    comentario = models.CharField(
        ("Comentarios"), max_length=150, null=True, blank=True)
    fechaPago = models.DateField(verbose_name="Fecha pago")
    comprobPago = models.ImageField(
        upload_to='media/pagos', null=False, default="comprobante de Pago", verbose_name="Comprobante de pago")
    confirm_pago = models.BooleanField(default=False)

    class Meta:
        ordering = ['fechaPago']

    def estado_pagos(self):
        if self.confirm_pago == False:
            return 'Revisar'
        else:
            return 'ok'

    def get_diferencia(self):
        dif = self.montoDebeAbonar - self.montoAbonado
        return dif

    def siAsociado(self):
        estado = False
        asociado = Asociado.objects.all()
        for a in asociado:
            if a.persona == self.personaAsociada:
                if a.estado == True:
                    estado = True
                else:
                    estado = False
        return estado
    
    @property
    def get_anio(self):
        fecha = self.fechaPago
        anio = fecha.year
        return anio
        
    @property
    def get_mes(self):
        fecha = self.fechaPago
        anio = fecha.month
        return anio

    
        
    @property
    def get_montoAbonado(self):
        monto = 0
        monto += self.montoAbonado
        return monto
    
    
        

class EscuelaTurnos(models.Model):
    nombre = models.CharField(max_length=8)
    cupo_turno = models.IntegerField()
    desde = models.TimeField()
    hasta = models.TimeField()

    def __str__(self):
        return f"{self.nombre}"
        
class EscuelaEntrenadores(models.Model):
    nombre = models.CharField(max_length=40)
    dni = models.IntegerField(null=True, blank=True)
    nacionalidad = models.CharField(max_length=12, default='Argentina')
    mail = models.EmailField(null=True, blank=True)
    telefono = models.IntegerField(default=0, null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    observacion = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre}"
    
    @property
    def edad(self):
        return date.today().year - self.fecha_nacimiento.year
    

class EscuelaFuncionesProfes(models.Model):
    funcion = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=100, null=True, blank=True)
    

    def __str__(self):
        return f"{self.funcion}"
    
    
    
class EscuelaAsignacTurno(models.Model):
    entrenador = models.ForeignKey(EscuelaEntrenadores, verbose_name=("Entrenador"), on_delete=models.CASCADE)
    turno = models.ForeignKey(EscuelaTurnos, on_delete=models.CASCADE)
    funcion = models.ForeignKey(EscuelaFuncionesProfes, on_delete=models.CASCADE)
    habilitado = models.BooleanField(default=False)
    hs_semanal = models.IntegerField(("Hs semanales"), default=0)
    seguro_escuela = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.entrenador}"

    
class EscuelaAsistencia(models.Model):
    fecha = models.DateField(("Fecha"), auto_now=False, auto_now_add=True)
    asociado = models.ForeignKey(Asociado, verbose_name=("Asociado"), on_delete=models.CASCADE)
    asistencia = models.BooleanField(("Asistencia"))
    comentario = models.CharField(("Comentario"),default="",null=True, blank=True ,max_length=100)

apps/escuela/forms.py
from django import forms
from apps.escuela.models import *
from django.forms.fields import DateField



class EscuelaPagosForm(forms.ModelForm):

    fechaPago = DateField(widget=forms.widgets.DateInput(
        attrs={'type': 'date', 'class': 'form-control'}), label='Fecha de Pago*:')
    comentario = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Breve comentario si necesitas'}), max_length=150, required=False, label='Comentario')
    comprobPago = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control'}), label='Adjuntar Comprobante de Pago*: jpg o png')

   
    class Meta:
        model = EscuelaPagos

        fields = ('opcionElegida', 'tipoPago', 'formaPago', 'montoDebeAbonar',
                  'montoAbonado', 'comentario', 'fechaPago', 'comprobPago')

        labels = {
       
        'montoAbonado':'Monto Abonado*:',
        'montoDebeAbonar':'Monto que debe abonar*:',
        'formaPago':'Forma de pago elegida*:',
        'opcionElegida': 'Seleccione la cuota que abonó*:',
        'tipoPago':'Tipo Asociado*:',
        }

        widgets = {
            'opcionElegida': forms.Select(attrs={'class': 'form-control'}),
            'tipoPago': forms.Select(attrs={'class': 'form-control'}),
            'formaPago': forms.Select(attrs={'class': 'form-control'}),
            'montoDebeAbonar': forms.Select(attrs={'class': 'form-control'}),
            'montoAbonado': forms.NumberInput(attrs={'class': 'form-control'}),
            'fechaPago': forms.DateInput(attrs={'class': 'form-control'}),
            'comprobPago': forms.FileInput(attrs={'class': 'form-control'}),

        }


class AsistenciaForm(forms.ModelForm):
    asociado = forms.ModelChoiceField(
        queryset=Asociado.objects.filter(estado=True, tipoAsociado=5))
    
    comentario = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Breve comentario si necesitas'}), max_length=150, required=False, label='Comentario')
    
    
    class Meta:
        model = EscuelaAsistencia
        
        fields = ('asociado', 'asistencia', 'comentario',)
        
        labels = {

           
        }

        widgets = {
            'asociado': forms.Select(attrs={'class': 'form-control'}),
           

        }


    

apps/escuela/views.py
from django.shortcuts import render
from apps.escuela.models import *
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin  # for create and update
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from apps.escuela.forms import EscuelaPagosForm, AsistenciaForm



# Create your views here.


class EscuelaPagoCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = EscuelaPagos
    template_name = 'escuela/form_pago_escuela.html'
    form_class = EscuelaPagosForm
    success_url = reverse_lazy('lista_pagos_escuela')
    success_message = "Hemos registrado tu pago! Lo estamos procesando"

    def get_context_data(self, **kwargs):
        context = super(EscuelaPagoCreate,
                        self).get_context_data(**kwargs)
        asociados = Asociado.objects.filter(persona=self.request.user)
        lista = []
        for asociado in asociados:
            lista.append(asociado)
        context['asociado'] = lista
        context['tipos'] = EscuelaFormasPago.objects.all()
        context['costos'] = EscuelaCosto.objects.all()
        return context
   
    
    def form_valid(self, form):
        asociados = Asociado.objects.filter(persona=self.request.user)
        lista = []
        for asociado in asociados:
            lista.append(asociado)
        form.instance.asociado = lista[-1]
        nuevo_pago = form.save(commit=False)
        asociado = form.instance.asociado
        nuevo_pago.save()
        
        template = render_to_string(
            'email/alerta_admin_PagoEscuela.html', {
                'asociado': asociado,
                'opcion_elegida': nuevo_pago.opcionElegida,
                'tipoAsociado': nuevo_pago.tipoPago,
                'vencimiento': asociado.get_vencimiento,
                'cuota': nuevo_pago.formaPago,
                'monto_debe_abonar':nuevo_pago.montoDebeAbonar,
                'monto_abonado': nuevo_pago.montoAbonado,
                'fecha_pago': nuevo_pago.fechaPago,
                'comentario': nuevo_pago.comentario,
            })
        subject = f"ALERTA NUEVO PAGO ESCUELA:  {asociado}"
        from_email = settings.EMAIL_HOST_USER
        to_email = settings.EMAIL_HOST_USER
        msg = EmailMessage(subject, template, from_email, [
                           to_email, 'triatloncba@gmail.com', 'triatloncba.infantojuvenil@gmail.com', 'carolinamonasterolo@gmail.com'])
        msg.content_subtype = "html"
        msg.fail_silently = False
        msg.send()

        
        
        
        
        
        return super().form_valid(form)

    


class EscuelaPagosList(ListView):
    model = EscuelaPagos
    template_name = 'escuela/lista_pagos_escuela.html'
    ordering = ['fechaPago', ]

    # def form_valid(self, form):
    #     form.instance.asociado = self.request.user
    #     return super().form_valid(form)

class EscuelaAsistenciaCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model=EscuelaAsistencia
    queryset = Asociado.objects.filter(estado=True, tipoAsociado=5)
    template_name='escuela/form_asistencia.html'
    form_class=AsistenciaForm
    success_url=reverse_lazy('asistencia')
    success_message="Se han guardado los cambios"

    def get_context_data(self, **kwargs):
        context = super(EscuelaAsistenciaCreate,
                        self).get_context_data(**kwargs)
        context['asociados'] = Asociado.objects.filter(
            estado=True, tipoAsociado=5)
        return context

apps/escuela/templates/escuela/form_asistencia.html
{% extends "base/index3.html" %}
{% load static %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container bg-opacity-50" >
            
<form  method="POST" class="needs-validation form-control bg-black bg-opacity-75 text-white"  enctype="multipart/form-data" onsubmit="send();">
    {% csrf_token %}
    {%  if user.is_authenticated %}
       
            <br>
            <h3 class="text-center">Registro Asistencia ESCUELA:</h3>
            <h5 class="text-center" style="color:#148F77"></h5>        
        
            
            
            {% for n in asociados %}
          <div class="row">
           
            <div class="col">{{n}}</div>

            <div class="col">
                <div class="form-check form-control-lg form-switch">
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked2" value={{form.asistencia.label}}
                <label class="form-check-label" for="flexSwitchCheckChecked2">{{form.asistencia.label}}</label>
            </div>
                
            </div>
           
            <div class="col">{{form.comentario}}</div>
            
          </div>
          {% endfor %}


    {% endif %}
</form>
</div>

    
    

            
{% endblock %}        

apps/escuela/templates/escuela/form_pago_escuela.html
{% extends "base/index3.html" %}
{% load static %}
{% block content %}

{% load crispy_forms_tags %}

<div class="container bg-opacity-50" >
            
<form  method="POST" class="needs-validation form-control bg-black bg-opacity-75 text-white"  enctype="multipart/form-data" onsubmit="send();">
    {% csrf_token %}
    {%  if user.is_authenticated %}
        {% if  asociado %}
            <br>
            <h3 class="text-center">Registra tu pago de ABONO MENSUAL ESCUELA:</h3>
            <h5 class="text-center" style="color:#148F77">{{request.user.first_name}} {{request.user.last_name}}</h5>        
        
            {% for s in asociado %}
                {% if forloop.last %}
                {% if s.persona == request.user %}
                    {% if s.get_vigente %}
                        {% if s.entrenador.id == 1 %}
                        
                            <h5 class="text-center" style="color:white">{{s.entrenador}}</h5>
                            <br>
                            
                            
                            <div class="form-control-btn-group">     
                                <div class="row-item">
                                    <label> {{form.opcionElegida.label}}</label>
                                    <select name="opcionElegida" id="id_opcionelegida" class="form-control" required>
                                        <option value='0'></option>
                                        {% for x in costos %}
                                        
                                        <option value="{{x.id}}">{{x}}</option>
                                        
                                        {% endfor %}
                                            
                                    </select>
                                </div>
                                <br>
                                <div class="row-item">
                                    <div> {{form.tipoPago.label}}</div>
                                        <select name="tipoPago" id="id_tipoPago" class="form-control" required> 
                                            <option value="{{s.entrenador}}" >{{s.entrenador}}</option>
                                        
                                        
                                        </select>
                                </div>
                                <br>
                                <div class="row-item">
                                    <div> {{form.formaPago.label}}</div>
                                        <select name="formaPago" id="id_formapago" class="form-control" required> 
                                            <option value='0'> --------</option>
                                            {% for x in costos %}
                                            
                                            <option value="{{x.formaPago}}" data-chained="{{x.id}}">{{x.formaPago}}</option>
                                           
                                            {% endfor %}
                                        </select>
                                </div>
                                <br>
                                <div class="row-item">
                                    <div> {{form.montoDebeAbonar.label}}</div>
                                        <select name="montoDebeAbonar" id="id_precio"  class="form-control" required> 
                                            <option value='0'> --------</option>
                                            {% for x in costos %}
                                            
                                            <option value="{{x.precio}}" data-chained="{{x.id}}">$ {{x.precio}}</option>
                                          
                                            {% endfor %}
                                        </select>
                                </div>
                                <br>
                                <div class="row-item">
                                    <label> {{form.montoAbonado.label}}</label>
                                    <div>{{form.montoAbonado}}</div>
                                </div>
                                <br>
                                <div class="row-item">
                                    <label> {{form.comentario.label}}</label>
                                    <div>{{form.comentario}}</div>
                                </div>
                                <br>
                                <div class="row-item">
                                    <label> {{form.fechaPago.label}}</label>
                                        <div> {{form.fechaPago}}</div>
                                </div>
                                <br>    
                                <div class="row-item">
                                    <label>{{form.comprobPago.label}}</label>
                                        <div>{{form.comprobPago}}</div>
                                </div>
                                <br>
                                <br>
                                {% comment %} <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                                    <label class="form-check-label" for="invalidCheck">
                                        Declaro haber leído y entendido los ......como asociado
                                        <a href="https://triatloncordoba.org/eventos/">triatloncordoba.org/eventos/ </a>
                                    </label>
                                </div> {% endcomment %}
                                <br>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                                    <label class="form-check-label" for="invalidCheck">
                                        Declaro que las imágenes adjuntas son copia fiel de su original.
                                    </label>
                                </div>
                                <br>
                                <div class="d-flex justify-content-end">
                                    <a class="btn btn-secondary" href={% url 'lista_pagos_escuela' %}>Cancelar</a>
                                    &nbsp;    
                                    <input id="btn" class="btn btn-primary" type="submit" value="Confirmar">
                                </div> 
                            </div>
                            <br><br><br>
                        {%  else %}
                        
                            <h4> Hola {{request.user.first_name|title}}:</h4> 
                            <br>
                            <h5>Tu entrenador debe ser "Escuela"</h5>
                            <p>En caso de necesitar cambiar tu Entrenador, por favor envianos un mail a triatloncba@gmail.com o a tesoreriatriatloncba@gmail.com</p>
                            <div class="d-flex justify-content-center">   
                                <a class="btn btn-danger" href={% url 'lista_pagos_escuela' %}>Cerrar</a>
                            </div>
                        {% endif %}
                    
                    {% else %}
                            
                            <h4> Hola {{request.user.first_name|title}}:</h4> 
                            <br>
                            <h5>Primero necesitas volver a Asociarte. Por favor ingresa por Carnet Asociado</h5>
                            <br>
                            <div class="d-flex justify-content-center">   
                                <a class="btn btn-outline-primary" href={% url 'carnet' %}>Ir a Carnet</a>
                            </div>
                        
                    {% endif %}

                {% endif %}
                {% endif %}
            {% endfor %}
        
        
        {% else %}
            <br><br><br>
                <h4> Hola {{request.user.first_name|title}}:</h4>            
                <h5>Primero necesitas Asociarte. Por favor ingresar por Carnet Asociado</h5>
                <br>
                <div class="d-flex justify-content-center">   
                    <a class="btn btn-outline-primary" href={% url 'carnet' %}>Ir a Carnet</a>
                </div>
        {% endif %}        
        
    {% endif %}
</form>
</div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="{% static 'registro/js/jquery.chained.min.js' %}"></script>

    
    <script>
     $(function(){
        $("#id_opcionelegida").val("{{ form.opcionElegida.id }}").change();
      
      
        $("#id_formapago").val("{{form.formaPago.id}}").change();
        $("#id_formapago").chained("#id_opcionelegida");
        $("#id_precio").val("{{form.precio.id}}").change();
        $("#id_precio").chained("#id_opcionelegida");
        
        
        });
    </script>
    
    

            
{% endblock %}        

apps/escuela/templates/escuela/lista_pagos_escuela.html
{% extends "base/index3.html" %}
{%  if user.is_authenticated %}

{% block content %}
{% load static %}

 <h2 class="text-white p-2 bg-black bg-opacity-50"><strong>Mis pagos mensuales Escuela </strong></h2>

<form method='POST' class=" form-control ">
    {% csrf_token %}
   
          
        
        
        
        <div style="overflow-x:auto; ">
            <table class = 'table'>
                <thead>
                    <tr class="table table-success">
                        {% comment %} <th >Nº</th> {% endcomment %}
                        <th >Estado</th>
                        <th >Fecha Pago</th>
                        <th >Nombre</th>
                        <th >Concepto</th>
                        <th >Monto Abonado</th>
                        <th >Tipo socio</th>
                        <th >Comprob Pago</th>
                    </tr>
                </thead>
                {% if object_list %}  
                    {% for c in object_list %}
                    
                        <tbody>
                            {% if c.asociado.persona == request.user %}
                                <tr>
                                    {% comment %} <td>{{c.id}}</td> {% endcomment %}
                                    {% if c.confirm_pago == False %}
                                    <th style="color:red">A confirmar</td>
                                        {% else %}
                                        <td><img src={% static 'registro/tilde2.png' %}  width="30" height="30"></td>
                                    {% endif %}    
                                    <td>{{c.fechaPago|date:"d/m/Y"}}</td>
                                    <td>{{c.asociado|title}} </td>
                                    <td>{{c.formaPago}}</td>
                                    <th>$ {{c.montoAbonado|floatformat:"-3g"}}</td>
                                 
                                    <td>{{c.tipoPago}}</td>
                                   

                                    <td><a href={{c.comprobPago.url}}><img src={{c.comprobPago.url}} width="20" height="20"></td></a>
                                    <tr>               
                           {% endif %}
                        </tbody>
                    {% endfor %}
                {% else%}
                    <br>
                    <h4>Aún no tienes pagos registrados</h4>
                {% endif %}    
            </table>
        </div> 
            
            <div class="d-flex justify-content-center">   
                <a class="btn btn-success" href={% url 'pagos_escuela'   %}>Informar un Pago</a>
            </div>

    
</form>   
     
{% endblock  %}
{% endif %}   