apps/socio/urls.py
from django import views
from django.urls import path, include
from . import views
from apps.socio.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


urlpatterns = [

    
    path('socios/', AsociadosList.as_view(), name='socios'),
    path('asociarse/', login_required(AsociadoCreate.as_view()), name='asociarse'),
    path('editar_socio/<pk>/', login_required(AsociadoEditar.as_view()), name='editar_socio'),
    path('pagos/', login_required(AsociadoPagoCreate.as_view()), name='pagos'),
    path('mensaje/', login_required(views.mensaje), name='mensaje'),
    
    path('lista_pagos_socio/', login_required(AsociadoPagosList.as_view()), name='lista_pagos_socio'),
    
    path('carnet/', login_required(AsociadoCertifList.as_view()), name='carnet'),
    
   

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = "apps.socio.views.error_404_view"

triaCba/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
  
    path('escuela/', include('apps.escuela.urls')),
    path('registro/', include('apps.registro.urls')),
    path('asociado/', include('apps.socio.urls')),
    path('inscripcion/', include('apps.inscripcion.urls')),
    path('', include('apps.usuarios.urls')),
    path('entrenadores/', include('apps.entrenadores.urls')),
    path('emails/', include('apps.emails.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),

    
    
    # path('', LoginView.as_view(template_name='accounts/login.html'), name = 'login')
    
    
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "apps.socio.views.error_404_view"
handler404 = "apps.usuarios.views.error_404_view"
handler404 = "apps.inscripcion.views.error_404_view"
handler404 = "apps.registro.views.error_404_view"
handler404 = "apps.emails.views.error_404_view"

apps/socio/models.py
from logging import PlaceHolder
from django.db import models
from django.utils import timezone
from datetime import datetime, date, timedelta
from ckeditor.fields import RichTextField
#from apps.registro.models import AsociadoCosto, AsociadoFormasPago, AsociadoTipo , EntrenadoresKempe
from apps.usuarios.models import Persona



# Create your models here.
class AsociadoTipo(models.Model):
    tipoAsociado = models.CharField(max_length=40)

    def __str__(self):
        return f"{self.tipoAsociado}"


class AsociadoFormasPago(models.Model):
    formaPago = models.CharField(max_length=40)
    
    class Meta:
        ordering = ['formaPago', ]

    def __str__(self):
        return f"{self.formaPago}"


class AsociadoCosto(models.Model):
    tipoSocio = models.ForeignKey(AsociadoTipo, default=1,on_delete=models.CASCADE, null=True)
    formaPago = models.ForeignKey(
        AsociadoFormasPago, default=1, on_delete=models.CASCADE, null=True)
    precio = models.IntegerField()
    
    

    def __str__(self):
        return f"{self.tipoSocio} - {self.formaPago} - $ {self.precio}"
   


class EntrenamientoTurno(models.Model):
    nombre = models.CharField(max_length=8)
    cupo_turno = models.IntegerField()
    desde = models.TimeField()
    hasta = models.TimeField()

    def __str__(self):
        return f"{self.nombre}"


class DiasEntrenamiento(models.Model):
    dias = models.CharField(("Días"), max_length=50)

    def __str__(self):
        return f"{self.dias}"


    
class EntrenadoresKempe(models.Model):
    nombre = models.CharField(max_length=25)
    cupo_entrenador = models.IntegerField(null=True, blank=True)
    turno = models.ForeignKey(EntrenamientoTurno, on_delete=models.CASCADE)
    mail = models.EmailField(null=True, blank=True)
    telefono = models.IntegerField(default=0, null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    dni = models.IntegerField(null=True, blank=True)
    nacionalidad = models.CharField(max_length=12, default='Argentina')
    observacion = models.CharField(max_length=50, null=True, blank=True)
    habilitado = models.BooleanField(default=False)
    seguro = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.nombre}"
    
    
class AsignarDiasEntrenamiento(models.Model):
    entrenador = models.ForeignKey(EntrenadoresKempe, verbose_name=("Entrenador"), on_delete=models.CASCADE)
    dias = models.ManyToManyField(DiasEntrenamiento, verbose_name=("Dias"))
    desde = models.TimeField(null=True, blank=True)
    hasta = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.dias}-{self.entrenador}-{self.desde}-{self.hasta}"

class AsociadoRequisitos(models.Model)    :
    requisitos = RichTextField()
    
    def __str__(self):
        return f"{self.requisitos}"
    


class Asociado(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now=True, blank=True)
    tipoAsociado = models.ForeignKey(
        AsociadoTipo, null=False, blank=False, on_delete=models.CASCADE, verbose_name='Tipo asociado')
    fecha_emision_emmac = models.DateField(auto_now=False, null = True ,
                                           blank=True )  # default=date(2000, 1, 1)
    emmac_file = models.ImageField(
        upload_to='media/emmac', null=True, blank=True, default="media/emmac/Sin_emmac.png")
    numero_emmac = models.CharField(
        ("numero Emmac"), max_length=10, default='s/d', blank=True)
    obra_social = models.CharField(max_length=60, null=False, blank=False)
    con_entrenador = models.CharField(
        max_length=2, choices=[('1', 'SI'), ('2', 'NO')], default=2)
    entrenador = models.ForeignKey(EntrenadoresKempe, on_delete=models.CASCADE, null=False,blank=False, default=12, verbose_name='Entrenador Kempes')
    responsable_tutor = models.CharField(max_length=40, null=True, blank=True,default='', help_text="campos obligatorios en caso de ser menor de 18 años")
    relacion_legal = models.CharField(
        max_length=2, choices=[('1', 'Madre'), ('2', 'Padre'), ('3', 'Tutor Legal')], default='1', help_text="campo obligatorios en caso de ser menor de 18 años", blank=True)
    dni_responsable = models.IntegerField(
        null=True, blank=True, help_text="campo obligatorios en caso de ser menor de 18 años")
    mail_responsable = models.EmailField(
        null=True, blank=True, help_text="campo obligatorios en caso de ser menor de 18 años")
    telefono_responsable = models.CharField(
        max_length=30,
        blank=True, null=True, help_text="campo obligatorios en caso de ser menor de 18 años")
    estado = models.BooleanField(default=False)
    asiste = models.BooleanField(default=False)
    
    
    
    def __str__(self):
        return f"{self.persona}"


    @property
    def get_vencimiento_emmac(self):
        vencimiento = self.fecha_emision_emmac + timedelta(days=365)
        return vencimiento
    
    @property
    def get_emmac_no_presentado(self):
        if self.fecha_emision_emmac == date(2000,1,1):
            return True
    

    @property
    def get_sit_emmac(self):
        if date.today() > self.get_vencimiento_emmac:
            return False
        else:
            return True
    
    @property
    def get_vencimiento(self):
        vencimiento = self.fecha + timedelta(days=365)
        return vencimiento
    
    
    @property
    def get_vigente(self):
        if self.get_vencimiento < date.today():
            return False
        else:
            return True
    
    # @property
    # def vigentes(self):
    #     cantidad = 0
    #     if self.get_vigente:
    #         cantidad += 1
    #     return cantidad
    
    
    @property
    def dias_vencer(self):
        if self.get_vencimiento >= date.today():
            self.estado=True
        else:
            self.estado=False
        return self.estado
    
    

    @property
    def get_estado(self):
        if self.dias_vencer and self.estado and self.get_sit_emmac:
            self.estado = True
        else:
           self.estado = False
        return self.estado
     
        
    @property
    def fecha_actual(self):
        fecha_hora = datetime.now()
        return fecha_hora 
    
   
    
    
        
        
    
class AsociadoPagos(models.Model):
    personaAsociada = models.ForeignKey(Persona, null=True, blank=True,
                                 on_delete=models.CASCADE, verbose_name='Persona Asociada')
    opcionElegida = models.ForeignKey(
        AsociadoCosto, null=True, blank=True, on_delete=models.CASCADE, verbose_name="Forma:")
    
    tipoAsociadoPago = models.CharField(
        max_length=40,  blank=True, null=True, verbose_name="Tipo:")
    formaPago = models.CharField(
        max_length=40,  blank=True, null=True, verbose_name="Forma pago")
    montoDebeAbonar = models.IntegerField(
        null=True, blank=True, verbose_name="Monto debe abonar:")
    montoAbonado = models.IntegerField(("Monto Abonado"), null=True)
    comentario = models.CharField(
        ("Comentarios"), max_length=150, null=True, blank=True)
    fechaPago = models.DateField(verbose_name="Fecha pago")
    comprobPago = models.ImageField(
        upload_to='media/pagos', null=True, default="comprobante de Pago", verbose_name="Comprobante")
    confirm_pago = models.BooleanField(default=False)
    

    class Meta:
        ordering = ['fechaPago']
    
    
    def estado_pagos(self):
        if self.confirm_pago == False:
            return 'Revisar'
        else:
            return 'ok'    
      
   
    def get_diferencia(self):
        dif = self.montoDebeAbonar - self.montoAbonado
        return dif
       
    def siAsociado(self):
        estado = False
        asociado = Asociado.objects.all()
        for a in asociado:
            if a.persona == self.personaAsociada:
                if a.estado == True:
                    estado = True
                else:
                    estado = False
        return estado
   
    
   
   
    

apps/escuela/views.py
from django.shortcuts import render
from apps.escuela.models import *
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin  # for create and update
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from apps.escuela.forms import EscuelaPagosForm, AsistenciaForm



# Create your views here.


class EscuelaPagoCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = EscuelaPagos
    template_name = 'escuela/form_pago_escuela.html'
    form_class = EscuelaPagosForm
    success_url = reverse_lazy('lista_pagos_escuela')
    success_message = "Hemos registrado tu pago! Lo estamos procesando"

    def get_context_data(self, **kwargs):
        context = super(EscuelaPagoCreate,
                        self).get_context_data(**kwargs)
        asociados = Asociado.objects.filter(persona=self.request.user)
        lista = []
        for asociado in asociados:
            lista.append(asociado)
        context['asociado'] = lista
        context['tipos'] = EscuelaFormasPago.objects.all()
        context['costos'] = EscuelaCosto.objects.all()
        return context
   
    
    def form_valid(self, form):
        asociados = Asociado.objects.filter(persona=self.request.user)
        lista = []
        for asociado in asociados:
            lista.append(asociado)
        form.instance.asociado = lista[-1]
        nuevo_pago = form.save(commit=False)
        asociado = form.instance.asociado
        nuevo_pago.save()
        
        template = render_to_string(
            'email/alerta_admin_PagoEscuela.html', {
                'asociado': asociado,
                'opcion_elegida': nuevo_pago.opcionElegida,
                'tipoAsociado': nuevo_pago.tipoPago,
                'vencimiento': asociado.get_vencimiento,
                'cuota': nuevo_pago.formaPago,
                'monto_debe_abonar':nuevo_pago.montoDebeAbonar,
                'monto_abonado': nuevo_pago.montoAbonado,
                'fecha_pago': nuevo_pago.fechaPago,
                'comentario': nuevo_pago.comentario,
            })
        subject = f"ALERTA NUEVO PAGO ESCUELA:  {asociado}"
        from_email = settings.EMAIL_HOST_USER
        to_email = settings.EMAIL_HOST_USER
        msg = EmailMessage(subject, template, from_email, [
                           to_email, 'triatloncba@gmail.com', 'triatloncba.infantojuvenil@gmail.com', 'carolinamonasterolo@gmail.com'])
        msg.content_subtype = "html"
        msg.fail_silently = False
        msg.send()

        
        
        
        
        
        return super().form_valid(form)

    


class EscuelaPagosList(ListView):
    model = EscuelaPagos
    template_name = 'escuela/lista_pagos_escuela.html'
    ordering = ['fechaPago', ]

    # def form_valid(self, form):
    #     form.instance.asociado = self.request.user
    #     return super().form_valid(form)

class EscuelaAsistenciaCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model=EscuelaAsistencia
    queryset = Asociado.objects.filter(estado=True, tipoAsociado=5)
    template_name='escuela/form_asistencia.html'
    form_class=AsistenciaForm
    success_url=reverse_lazy('asistencia')
    success_message="Se han guardado los cambios"

    def get_context_data(self, **kwargs):
        context = super(EscuelaAsistenciaCreate,
                        self).get_context_data(**kwargs)
        context['asociados'] = Asociado.objects.filter(
            estado=True, tipoAsociado=5)
        return context

apps/socio/templates/socio/asociado_editar.html
{% extends "base/index3.html" %}
{% block content %}
{% load crispy_forms_tags %}
 

    <div class="container">
        <form  method="POST" class="needs-validation form-control text-white bg-black bg-opacity-75" enctype="multipart/form-data" >
            {% csrf_token %}
            {%  if user.is_authenticated%}
                <br>
                <h3 class="text-center">Modificar tus datos de Asociado:</h3>
                <h4 class="text-center" style="color:white">{{request.user.first_name}} {{request.user.last_name}}</h4>
                <br>
                
                   
                <b><p> ! Si quieres cambiar de entrenador debes solicitarlo vía email a tesoreriatriatloncba@gmail.com</p>
                <p> ! Si subes tu nuevo emmac, debes informarnos vía email a tesoreriatriatloncba@gmail.com para que cambiemos la fecha de emisión. Gracias</p></b>
                        
                        {{form.con_entrenador.label}}
                        {{form.con_entrenador}}

                     <br>
                     
                        {{form.emmac_file.label}}
                        {{form.emmac_file}}
                        <br><br>

                        {{form.numero_emmac.label}}                        
                        {{form.numero_emmac}}

                        {{form.obra_social.label}}                        
                        {{form.obra_social}}

                        <br>
                       
                        
                            {{form.responsable_tutor.label}}
                            {{form.responsable_tutor}}
                        
                            {{form.relacion_legal.label}}
                            {{form.relacion_legal}} 
                 
                            {{form.dni_responsable.label}}
                            {{form.dni_responsable}}
                            
                            {{form.mail_responsable.label}}
                            {{form.mail_responsable}}

                            {{form.telefono_responsable.label}}
                            {{form.telefono_responsable}}

                       
                        <br>

                     

                <br>
                <div class="d-flex justify-content-end">                  
                    <a type="reset" class="btn btn-secondary" href={% url 'carnet' %}>Cancelar</a>
                    &nbsp;                 
                    <input type="submit" class="btn btn-sm btn-primary" value="Confirmar">
                </div>
            {% else %}
                <p> No hay nadie logueado</p>
            {% endif %} 
        </form>

    </div>    
   
            
{% endblock  %}

apps/socio/templates/socio/form_asociarse_2.html
{% extends "base/index3.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="2164440" />
      </requestFiltering>
    </security>
</system.webServer>

    <div class="container">
        <form  method="POST" class="needs-validation form-control text-white bg-black bg-opacity-75" enctype="multipart/form-data" onsubmit="send();move();">
            {% csrf_token %}
            {%  if user.is_authenticated%}
                <br>
                <h3 class="text-center">Registro para Asociarse de:</h3>
                <h4 class="text-center" style="color:white">{{request.user.first_name}} {{request.user.last_name}}</h4>
               
                
                <br>
               
                     <div class="row">
                       {#{form |crispy}#}
                    </div>
                <br>
                        
                      
                        {{form.con_entrenador.label}}
                        {{form.con_entrenador}}

                        {{form.entrenador.label}}
                        {{form.entrenador}}
                        <br>

                        {{form.fecha_emision_emmac.label}}
                        {{form.fecha_emision_emmac}}
                        
                        {{form.emmac_file.label}}
                        {{form.emmac_file}}
                        
                        {{form.numero_emmac.label}}                        
                        {{form.numero_emmac}}
                        <br>
                        {{form.obra_social.label}}                        
                        {{form.obra_social}}

                        <br>
                        {% if request.user.get_edad < 18 %}
                        <p> Tienes {{request.user.get_edad}} años de edad, debes completar la siguiente información:</p>
                        
                            {{form.responsable_tutor.label}}
                            {{form.responsable_tutor}}
                        
                            {{form.relacion_legal.label}}
                            {{form.relacion_legal}} 
                 
                            {{form.dni_responsable.label}}
                            {{form.dni_responsable}}
                            
                            {{form.mail_responsable.label}}
                            {{form.mail_responsable}}

                            {{form.telefono_responsable.label}}
                            {{form.telefono_responsable}}

                        {% endif %}
                        <br>

                            <div class="form-control-btn-group">     
                                <div class="row-item">
                                    <label> {{form2.opcionElegida.label}}</label>
                                    <select name="opcionElegida" id="id_opcionelegida" class="form-control" required>
                                        <option value='0'>Elija una opción</option>
                                        {% for x in costos %}
                                        
                                        <option value="{{x.id}}" >{{x}}</option>
                                       
                                        {% endfor %}
                                            
                                    </select>
                                </div>
                                <br>
                               
                                <div class="row-item">
                                    <div> {{form2.tipoAsociadoPago.label}}</div>
                                        <select style="color:red; font-weight: bold;" name="tipoAsociadoPago" id="id_tipoasociadopago" class="form-control" required> 
                                        <option value='0'> --------</option>
                                        {% for x in costos %}
                                       
                                            <option  value="{{x.tipoSocio}}" data-chained="{{x.id}}"><b>{{x.tipoSocio}}</b></option>
                                       
                                        {% endfor %}
                                        </select>
                                </div>
                                
                                <div class="row-item">
                                    <div> {{form2.formaPago.label}}</div>
                                        <select style="color:red; font-weight: bold;" name="formaPago" id="id_formapago" class="form-control" required> 
                                            <option value='0'> --------</option>
                                            {% for x in costos %}
                                            
                                            <option value="{{x.formaPago}}" data-chained="{{x.id}}">{{x.formaPago}}</option>
                                            
                                            {% endfor %}
                                        </select>
                                </div>
                                
                                <div class="row-item">
                                    <div> {{form2.montoDebeAbonar.label}}</div>
                                        <select style="color:red; font-weight: bold;" name="montoDebeAbonar" id="id_precio"  class="form-control" required> 
                                            <option value='0'> --------</option>
                                            {% for x in costos %}
                                           
                                            <option value="{{x.precio}}" data-chained="{{x.id}}">$ {{x.precio}}</option>
                                            
                                            {% endfor %}
                                        </select>
                                </div>
                            
                                <br>
                                <div class="row-item">
                                    <label> {{form2.montoAbonado.label}}</label>
                                    <div>{{form2.montoAbonado}}</div>
                                </div>
                                <br>
                                <div class="row-item">
                                    <label> {{form2.comentario.label}}</label>
                                    <div>{{form2.comentario}}</div>
                                </div>
                                <br>
                                <div class="row-item">
                                    <label> {{form2.fechaPago.label}}</label>
                                        <div> {{form2.fechaPago}}</div>
                                </div>
                                <br>    
                                <div class="row-item">
                                    <label>{{form2.comprobPago.label}}</label>
                                        <div>{{form2.comprobPago}}</div>
                                </div>
                 
                  
                                <br>

                <div class="form-check">
                    <p><b> Al presionar 'Confirmar' declaro que:</b></p>
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                    <label class="form-check-label" for="invalidCheck">
                        Las imágenes que adjunto son copia fiel del original
                    </label>
                    <br>
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                    <label class="form-check-label" for="invalidCheck">
                        Los datos consignados en el presente formulario son verdaderos
                    </label>
                    <br>
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                    <label class="form-check-label" for="invalidCheck">
                        Entiendo y acepto el período de vigencia como persona asociada en relación a la fecha de alta y opción de pago  elegida
                    </label>
                    <br>
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                    <label class="form-check-label" for="invalidCheck">
                       Acepto recibir información de la Asociación Cordobesa de Triatlón a través del correo electrónico consignado
                    </label>
                </div>        







                <div class="d-flex justify-content-end">
                    <a type="reset" class="btn btn-secondary" href={% url 'carnet' %}>Cancelar</a>
                    &nbsp;                 
                    <input id="btn" type="submit" class="btn btn-sm btn-primary" value="Confirmar">
                </div>
            {% else %}
                <p> No hay nadie logueado</p>
            {% endif %} 
        </form>
        <br><br><br>

    </div>    
   

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="{% static 'registro/js/jquery.chained.min.js' %}"></script>

    
   <script>
     $(function(){
        $("#id_opcionelegida").val("{{ form2.opcionElegida.id }}").change();
       
        $("#id_tipoasociadopago").val("{{form2.tipoAsociadoPago.id}}").change();
        $("#id_tipoasociadopago").chained("#id_opcionelegida");
        $("#id_formapago").val("{{form2.formaPago.id}}").change();
        $("#id_formapago").chained("#id_opcionelegida");
        $("#id_precio").val("{{form2.precio.id}}").change();
        $("#id_precio").chained("#id_opcionelegida");
        
        
        });
    </script>
    
            
{% endblock  %}



 

apps/socio/templates/socio/lista_pagos_socio.html
{% extends "base/index3.html" %}
{%  if user.is_authenticated %}

{% block content %}
{% load static %}

 <h2 class="text-white bg-black bg-opacity-50"><strong>Mis pagos Asociación </strong></h2>

<form method='POST' class=" form-control">
    {% csrf_token %}
   
          
        
        
        
        <div style="overflow-x:auto; ">
            <table class = 'table'>
                <thead>
                    <tr class="table table-info">
                        {% comment %} <th >Nº</th> {% endcomment %}
                        <th >Estado</th>
                        <th >Fecha Pago</th>
                        <th >Nombre</th>
                        <th >Forma Pago</th>
                        <th >Monto Abonado</th>
                        <th >Tipo socio Abonado</th>
                        <th >Comprob Pago</th>
                    </tr>
                </thead>
                {% if asociadopagos_list %}  
                    {% for c in asociadopagos_list %}
                        <tbody>
                            {% if c.personaAsociada == request.user %}
                                <tr>
                                    {% comment %} <td>{{c.id}}</td> {% endcomment %}
                                    {% if c.confirm_pago == False %}
                                    <th style="color:red">A confirmar</td>
                                        {% else %}
                                        <td><img src={% static 'registro/tilde2.png' %}  width="30" height="30"></td>
                                    {% endif %}    
                                    <td>{{c.fechaPago|date:"d/m/Y"}}</td>
                                    <td>{{c.personaAsociada.first_name|title}} {{c.personaAsociada.last_name|title}}</td>
                                    <td>{{c.formaPago}}</td>
                                    <th>$ {{c.montoAbonado|floatformat:"-3g"}}</td>
                                    <td>{{c.opcionElegida.tipoSocio}}</td>
                                    <td><a href={{c.comprobPago.url}}><img src={{c.comprobPago.url}} width="20" height="20"></td></a>
                                    <tr>               
                            {% endif %}
                        </tbody>
                    {% endfor %}
                {% else%}
                    <br>
                    <h4>Aún no tienes pagos registrados</h4>
                {% endif %}    
            </table>
        </div> 
            
            <div class="d-flex justify-content-center">   
                <a class="btn btn-primary" href={% url 'pagos'   %}>Informar un Pago</a>
            </div>

    
</form>   
     
{% endblock  %}
{% endif %}   

apps/socio/templates/socio/mensaje_pago.html
{% extends "base/index3.html" %}
       

{% block content %}

<form method = 'POST' action="base/index3.html">
        {% csrf_token %}
        <h1>Gracias  {{object.nombres}} {{object.apellido}}, tu pago ha sido registrado. 
            Aparecerá en en lista una vez confirmada la transferencia.  </h1>
        <button class="btn btn-danger" type="submit">Continuar</button>
      
       
</form>

       
{% endblock %}